export const parajamaah: Jamaah[] = [
  {
    id: 1,
    name: "John Doe",
    gendermale: true,
    age: 30,
    negara: "indonesia",
    rombongan: "al-syahid",
    lat: -5.361766,
    lng: 105.225637,
    temp: 37.5,
    humid: 60,
  },
  {
    id: 2,
    name: "Jane Doe",
    gendermale: false,
    age: 54,
    negara: "indonesia",
    rombongan: "al-syahid",
    lat: -5.363089,
    lng: 105.225106,
    temp: 36.9,
    humid: 55,
  },
  {
    id: 3,
    name: "Michael Smith",
    gendermale: true,
    age: 41,
    negara: "indonesia",
    rombongan: "al-syahid",
    lat: -5.373362,
    lng: 105.230142,
    temp: 38.2,
    humid: 62,
  },
  {
    id: 4,
    name: "Emily Johnson",
    gendermale: false,
    age: 33,
    negara: "indonesia",
    rombongan: "al-syahid",
    lat: -5.373682,
    lng: 105.229958,
    temp: 36.6,
    humid: 58,
  },
  {
    id: 5,
    name: "David Lee",
    gendermale: true,
    age: 39,
    negara: "indonesia",
    rombongan: "al-syahid",
    lat: -5.373991,
    lng: 105.237774,
    temp: 37.0,
    humid: 63,
  },
  {
    id: 6,
    name: "Emma Chen",
    gendermale: false,
    age: 28,
    negara: "indonesia",
    rombongan: "al-zaitun",
    lat: -5.396602,
    lng: 105.258664,
    temp: 37.8,
    humid: 56,
  },
  // Add more jamaah data here up to 20 items
];
// table;

export const CardsMonitorJamaah: CardMonitorJamaah[] = [
  {
    id: 1,
    tittle: "Jumlah Jamaah",
    jumlah: parajamaah.length,
  },
  {
    id: 2,
    tittle: "Jamaah Pria",
    jumlah: parajamaah.filter((person) => person.gendermale).length,
  },
  {
    id: 3,
    tittle: "Jamaah Wanita",
    jumlah: parajamaah.filter((person) => !person.gendermale).length,
  },

  {
    id: 4,
    tittle: "Jumlah Jamaah Lansia",
    jumlah: parajamaah.filter((person) => person.age > 50).length,
  },
];
